name: gitartwork from a contribution graph

on: 
  push:

permissions:
  contents: write  # Memberikan izin untuk menulis ke repository

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jasineri/gitartwork@v1
        with:
          # Gunakan username pemilik repository (bukan jasineri jika bukan pemilik repo)
          user_name: ${{ github.albedoes }}
          # Teks yang ditampilkan di contribution graph
          text: Dika H.P

      - uses: jasineri/simple-push-action@v1
